apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    type: service
  namespace: 3-tier
spec:
  type: ClusterIP
  ports:
    - targetPort: 5000
      port: 5000
  selector:
    type: app-backend
...
