apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    type: service
  namespace: 3-tier
spec:
  type: ClusterIP
  ports:
    - targetPort: 27017
      port: 27017
  selector:
    type: db
...
